Total value of portfolio:  48595
Profit: 150
Total value of portfolio:  48661
Profit: 66
Total value of portfolio:  47637
Loss: -1024
Total value of portfolio:  49074
Profit: 1437
Total value of portfolio:  48821
Loss: -253
Total value of portfolio:  48495
Loss: -326
Total value of portfolio:  46238
Loss: -2257
Total value of portfolio:  45140
Loss: -1098
Total value of portfolio:  45428
Profit: 288
Total value of portfolio:  44645
Loss: -783
Total value of portfolio:  45758
Profit: 1113
Total value of portfolio:  45682
Loss: -76
Total value of portfolio:  45566
Loss: -116
Total value of portfolio:  46371
Profit: 805
Total value of portfolio:  46382
Profit: 11
Total value of portfolio:  45936
Loss: -446
Total value of portfolio:  46359
Profit: 423
Total value of portfolio:  46067
Loss: -292
Total value of portfolio:  45469
Loss: -598
Total value of portfolio:  45238
Loss: -231
Total value of portfolio:  45128
Loss: -110
Total value of portfolio:  45318
Profit: 190
Total value of portfolio:  45465
Profit: 147
Total value of portfolio:  46316
Profit: 851
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x735de250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pro-api.coinmarketcap.com', port=443): Max retries exceeded with url: /v1/cryptocurrency/quotes/latest?symbol=BTC%2CETH%2CADA%2CDOGE%2CATOM%2CDOT%2CLTC%2CXLM%2CXRP%2CXMR%2CBCH%2CMATIC%2CSOL&convert=GBP (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x735de250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/pythonScripts/totalportfolio.py", line 26, in <module>
    response = requests.get(api_endpoint, params=params, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pro-api.coinmarketcap.com', port=443): Max retries exceeded with url: /v1/cryptocurrency/quotes/latest?symbol=BTC%2CETH%2CADA%2CDOGE%2CATOM%2CDOT%2CLTC%2CXLM%2CXRP%2CXMR%2CBCH%2CMATIC%2CSOL&convert=GBP (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x735de250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Total value of portfolio:  47171
Profit: 855
Total value of portfolio:  47761
Profit: 590
Total value of portfolio:  47563
Loss: -198
Weekly PnL: Profit: 2435
Total value of portfolio:  47527
Loss: -36
Total value of portfolio:  47736
Profit: 209
Total value of portfolio:  49558
Profit: 1822
Total value of portfolio:  50045
Profit: 487
Total value of portfolio:  50181
Profit: 136
Total value of portfolio:  52959
Profit: 2778
Total value of portfolio:  53377
Profit: 418
Weekly PnL: Profit: 5814
Total value of portfolio:  57205
Profit: 3828
Total value of portfolio:  57636
Profit: 431
Total value of portfolio:  58770
Profit: 1134
Total value of portfolio:  58403
Loss: -367
Total value of portfolio:  56398
Loss: -2005
Total value of portfolio:  56546
Profit: 148
Total value of portfolio:  58021
Profit: 1475
Weekly PnL: Profit: 4644
Total value of portfolio:  61463
Profit: 3442
Total value of portfolio:  60803
Loss: -660
Total value of portfolio:  60424
Loss: -379
Total value of portfolio:  60869
Profit: 445
Total value of portfolio:  58900
Loss: -1969
Total value of portfolio:  60122
Profit: 1222
Total value of portfolio:  60665
Profit: 543
Weekly PnL: Profit: 2644
Total value of portfolio:  60022
Loss: -643
Total value of portfolio:  62520
Profit: 2498
Total value of portfolio:  59192
Loss: -3328
Total value of portfolio:  61139
Profit: 1947
Profit: 1947
Monthly PnL: Profit: 15821
Total value of portfolio:  61585
Profit: 446
Profit: 446
Total value of portfolio:  63937
Profit: 2352
Profit: 2352
Total value of portfolio:  64163
Profit: 226
Weekly PnL: Profit: 3498
Profit: 226
Weekly PnL: Profit: 3498
Total value of portfolio:  64786
Profit: 623
Profit: 623
Total value of portfolio:  62805
Loss: -1981
Loss: -1981
Total value of portfolio:  63521
Profit: 716
Profit: 716
Total value of portfolio:  63694
Profit: 173
Profit: 173
Total value of portfolio:  63195
Loss: -499
Loss: -499
Total value of portfolio:  60005
Loss: -3190
Loss: -3190
Total value of portfolio:  59470
Loss: -535
Weekly PnL: Loss: -4693
Loss: -535
Weekly PnL: Loss: -4693
Total value of portfolio:  58852
Loss: -618
Loss: -618
Total value of portfolio:  59861
Profit: 1009
Profit: 1009
Total value of portfolio:  57592
Loss: -2269
Loss: -2269
Total value of portfolio:  59818
Profit: 2226
Profit: 2226
Total value of portfolio:  63037
Profit: 3219
Profit: 3219
